name: workshops
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11 
  - util-linux
  - pip:
    - biopython
    - jupyterlab
    - notebook
    - matplotlib
    - numpy
    - pandas
