name: workshops
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - util-linux
  - pysam
  - biopython
  - matplotlib
  - seaborn
  - numpy
  - pandas
  - pip:
    - jupyterlab
    - notebook
